"""
runner.py — Parallel LLM Execution Layer

Fires all (prompt × test_case) pairs concurrently using asyncio.gather().
A semaphore caps concurrency to stay within Groq's free-tier rate limits.

Key design choices:
  - Each call is independent: a failure in one does NOT cancel others
    (return_exceptions=True in gather).
  - Semaphore prevents rate-limit hammering on free-tier accounts.
  - The {input} placeholder in prompts is replaced here with the actual
    test case text — no subprocess, no eval(), no shell=True.

Security:
  - Prompt text is already generated by the Generator Agent — it originated
    from a validated, length-bounded task string, not raw user input.
  - Test case inputs are validated in main.py before reaching here.
  - raw_output is stored as a plain string — never deserialized by LangChain.

Written for: langchain==1.3.11, langchain-core==1.4.8, langchain-groq==1.1.2
"""

import asyncio
import logging
import os

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_groq import ChatGroq

from models import GeneratedPrompts, PromptResult

logger = logging.getLogger(__name__)

_DEFAULT_RUNNER_MODEL = "openai/gpt-oss-20b"
_DEFAULT_MAX_CONCURRENT = 6


def _resolve_prompt(template: str, test_input: str) -> str:
    """Replace the {input} placeholder. Falls back to appending the input."""
    if "{input}" in template:
        return template.replace("{input}", test_input)
    # Defensive fallback: append input on a new line
    return f"{template}\n\nInput:\n{test_input}"


async def _run_single(
    label: str,
    prompt_template: str,
    test_case_id: str,
    test_case_input: str,
    llm: ChatGroq,
    semaphore: asyncio.Semaphore,
) -> PromptResult | None:
    """Execute one (prompt, test_case) pair under a concurrency semaphore.

    Accepts a pre-built ChatGroq instance (constructed once in run_all_parallel)
    rather than creating a new object per call — avoids N object constructions
    for N parallel tasks.

    Returns None on failure so gather() can collect partial results.
    """
    async with semaphore:
        try:
            resolved = _resolve_prompt(prompt_template, test_case_input)

            messages = [
                SystemMessage(content=resolved),
                HumanMessage(content=test_case_input),
            ]

            response = await llm.ainvoke(messages)
            raw = response.content
            if not isinstance(raw, str):
                raw = str(raw)

            raw = raw.strip()

            # P2: Guard against empty LLM output — evaluating an empty string
            # produces meaningless scores and pollutes the report.
            if not raw:
                logger.warning(
                    "Runner returned empty output — prompt=%s, test_case=%s. Skipping.",
                    label,
                    test_case_id,
                )
                return None

            return PromptResult(
                prompt_label=label,
                prompt_text=prompt_template,
                test_case_id=test_case_id,
                test_case_input=test_case_input,
                raw_output=raw,
            )

        except Exception as exc:
            logger.warning(
                "Runner call failed — prompt=%s, test_case=%s: %s",
                label,
                test_case_id,
                type(exc).__name__,   # log type only, not full message (may contain API content)
            )
            return None


async def run_all_parallel(
    prompts: GeneratedPrompts,
    test_cases: list[dict],
    api_key: str,
) -> list[PromptResult]:
    """Run 3 prompts × N test cases in parallel and return all valid results.

    ChatGroq is constructed ONCE here and passed to every _run_single coroutine.
    RUNNER_MODEL and MAX_CONCURRENT are read here (not at import time) so that
    load_dotenv() in main() has already populated os.environ.

    Args:
        prompts:    Three prompt templates from the Generator Agent.
        test_cases: List of {"id": str, "input": str} dicts.
        api_key:    Groq API key.

    Returns:
        List of PromptResult objects (failures silently skipped with a warning).
    """
    model = os.environ.get("RUNNER_MODEL", _DEFAULT_RUNNER_MODEL)
    max_concurrent = int(os.environ.get("MAX_CONCURRENT", str(_DEFAULT_MAX_CONCURRENT)))

    # Build the LLM client once — shared across all parallel coroutines.
    # ChatGroq is thread-safe for concurrent ainvoke() calls.
    llm = ChatGroq(
        model=model,
        temperature=0.3,
        max_tokens=600,
        timeout=30,         # Prevent indefinite hang on slow Groq responses
        groq_api_key=api_key,
        max_retries=2,
    )

    semaphore = asyncio.Semaphore(max_concurrent)

    prompt_map = {
        "A": prompts.prompt_a,
        "B": prompts.prompt_b,
        "C": prompts.prompt_c,
    }

    tasks = [
        _run_single(
            label=label,
            prompt_template=text,
            test_case_id=tc["id"],
            test_case_input=tc["input"],
            llm=llm,
            semaphore=semaphore,
        )
        for label, text in prompt_map.items()
        for tc in test_cases
    ]

    raw = await asyncio.gather(*tasks, return_exceptions=True)

    results: list[PromptResult] = []
    for item in raw:
        if isinstance(item, Exception):
            logger.warning("Uncaught exception in gather: %s", type(item).__name__)
        elif item is not None:
            results.append(item)

    return results
